spring:
  data:
    redis:
      url: rediss://default:AZgWAAIncDI2YTg1NjJiZDI2MGM0ZDI5YjIwMTc1ZTI3NmZmZTlkYnAyMzg5MzQ@becoming-sculpin-38934.upstash.io:6379
      ssl: 
        enabled: false
  application:
    name: partystapp

  datasource:
    url: jdbc:postgresql://dpg-d4atribipnbc73ai9360-a.oregon-postgres.render.com:5432/partyst
    username: administrator
    password: H6Zwj6TSlL8htqwUD4hlvelwF53eSWFB
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-test-query: SELECT 1
      connection-timeout: 30000   # espera 30s antes de marcar timeout
      validation-timeout: 5000    # 5s para validar conex
      max-lifetime: 1800000       # 30 min
      keepalive-time: 300000      # env√≠a ping cada 5 min
      idle-timeout: 600000        # 10 min

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
            use_jdbc_metadata_defaults: false
    show-sql: true
  jdbc:
    template:
      fetch-size: 500

  output:
    ansi:
      enabled: ALWAYS

server:
    port: 8080

application:
  security:
    jwt:
      secret-key: SDFSDFSDFadadasFASASDaasas23asaDSA13dASda12
      expiration: 86400000 
      refresh-token:
        expiration: 604800000

microservices:
  notifications:
    url: https://notifications-service-mkdx.onrender.com
    timeout: 10000